name: Compiles

on:
  pull_request:
  repository_dispatch:
    types: [shared-docker-linux-builders-updated]

concurrency:
  group: compiles-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag:
          - latest
          - release

    name: Compiles with ${{ matrix.tag }} Pony compiler
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder:${{ matrix.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Compile
        run: |
          make credo
