name: Lint Markdown

on: pull_request

concurrency:
  group: lint-markdown-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Lint Markdown files
        uses: docker://ghcr.io/super-linter/super-linter:v7.2.1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            VALIDATE_ALL_CODEBASE: true
            VALIDATE_MD: true
