name: Verify Changelog

on: pull_request_target

permissions:
  contents: read

jobs:
  verify-changelog:
    name: Verify CHANGELOG.md is valid
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/changelog-tool:release
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Verify CHANGELOG
        run: changelog-tool verify
